
on:
  schedule:
    - cron: '45 18 * * *'
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install wget curl unzip git
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean
          sudo timedatectl set-timezone Asia/Shanghai

      - name: Download file
        run: |
          sudo mkdir -p /tmp/smartdns
          sudo chown $USER:$GROUPS /tmp/smartdns
          wget https://github.com/felixonmars/dnsmasq-china-list/archive/refs/heads/master.zip -O /tmp/smartdns/master.zip
          sudo unzip /tmp/smartdns/master.zip -d /tmp/smartdns/

      - name: Convert server to nameserver
        run: |
          cd /tmp/smartdns/dnsmasq-china-list-master
          set -e
          sudo make smartdns SERVER=cn 2>&1 | sudo tee make.log

      - name: Upload make log
        uses: actions/upload-artifact@v4
        with:
          name: make-log
          path: /tmp/smartdns/dnsmasq-china-list-master/make.log

      - name: Set version tag
        id: set_version
        run: |
          VERSION=$(date +'%Y%m%d%H%M%S')  # 生成基于当前时间的版本号
          echo "VERSION=${VERSION}" >> $GITHUB_ENV  # 将版本号设置为环境变量
      - name: Copy generated files to repo
        run: |
          cp /tmp/smartdns/dnsmasq-china-list-master/*.raw.txt ./smartdns
          cp /tmp/smartdns/dnsmasq-china-list-master/*.smartdns.conf ./smartdns

      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add *.raw.txt *.smartdns.conf
          if ! git diff --cached --quiet; then
            git commit -m "Update SmartDNS files - version ${{ env.VERSION }}"
            git push
          else
            echo "No changes to commit."
          fi

      - name: Upload to release
        uses: softprops/action-gh-release@v0.1.15
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: smartdns-release-${{ env.VERSION }}  # 使用生成的版本号
          files: |
            /tmp/smartdns/dnsmasq-china-list-master/*.raw.txt
            /tmp/smartdns/dnsmasq-china-list-master/*.smartdns.conf           

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          retain_days: 7
          keep_minimum_runs: 7
